name: Docker Image CI

on:
  push:
    branches: [ "main" ]


jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Hacer checkout
        uses: actions/checkout@v4

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Install dependencies
        run: composer install 

      - name: Execute test
        run: vendor/bin/phpunit --testdox tests

  build:
    nedds: tests
    # si ubuntu saca una version incompatible petará
    runs-on: ubuntu-latest

    steps:
    # sirve para descargar y traer a nuestra máquina virtual probablemente con un git clone
    - name: Hacer checkout
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ${{ secrets.DOCKER_USER }}/calculadora:latest
