name: Docker Image CI

on:
  push:
    branches: [ "main" ]


jobs:
  build:
    # si ubuntu saca una version incompatible petará
    runs-on: ubuntu-latest

    steps:
    # sirve para descargar y traer a nuestra máquina virtual probablemente con un git clone
    - name: Hacer checkout
      uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_TOKEN }}
        
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build the Docker image
      run: docker build -t jmp23/calculadora:$(date +%s)
    - name: Subiendo Imagen
      run: docker push jmp23/calculadora:latest
